# PostgreSQL
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=admin
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/quarkus

# Hibernate
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true

# Puerto HTTP
quarkus.http.port=8080

# --- OpenAPI / Swagger (ruta por defecto: /q/swagger-ui o /openapi) ---
quarkus.smallrye-openapi.path=/openapi

# --- JWT verification (MP-JWT) ---
# Localización de la clave pública para verificar tokens
mp.jwt.verify.publickey.location=jwt/publicKey.pem

# Emisor (issuer) que usarás al crear tokens
mp.jwt.verify.issuer=https://apitienda.local

# Opcional: audiencias permitidas (separadas por comas)
# mp.jwt.verify.audiences=account

# Habilitar smallrye-jwt (si es necesario)
quarkus.smallrye-jwt.enabled=true

# (Opcional) Para desarrollo: logging
quarkus.log.category."io.smallrye.jwt".level=DEBUG

